### ISSUE TITLE
兄弟，程序能否再读取更多的信息呢？如地区，乡镇之类的

### ISSUE THREAD

**Issue by nottellyou** [XY-JX/qqwry#1]
兄弟，程序能否再读取更多的信息呢？如地区，乡镇之类的。

还有，是否用这种数据格式导入过sqlite3的数据库里，对比一下查询性能？

**Comment by XY-JX** [comment]
第1个问题地区乡镇极不准确，因为你要知道，用户的ip都是随机的。
第2个问题，需要你自己测试

**Comment by XY-JX** [comment]
第1个问题地区乡镇极不准确，因为你要知道，用户的ip都是随机的。
第2个问题，需要你自己测试

**Comment by nottellyou** [comment]
兄弟，你有办法循环读取纯真数据库IP的方法吗？小弟水平有限，写不出来读纯真数据库的方法。

如果你有这样的程序，可以分享一下。我导出IP到sqlite3后，给你一份。

**Comment by XY-JX** [comment]
找个第3方工具，或者找现成的数据直接导入，纯真数据库也是会更新的。如果要考虑准确性还要考虑后期维护的问题。

**Comment by XY-JX** [comment]
如果自己手写的话可以参考当前库代码

**Comment by nottellyou** [comment]
你说的对，IP不是固定的，地经常变动，这点我没想到。
